// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using la_mia_pizzeria_post.Data;

#nullable disable

namespace la_mia_pizzeria_post.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221007131639_AddCategoriesTable")]
    partial class AddCategoriesTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("la_mia_pizzeria_crud_mvc.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizze classiche"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pizze bianche"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizze vegetariane"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Pizze di mare"
                        });
                });

            modelBuilder.Entity("la_mia_pizzeria_crud_mvc.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "La classica pizza",
                            Name = "Margherita",
                            Photo = "margherita.png",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "La classica pizza piccante",
                            Name = "Diavola",
                            Photo = "diavola.png",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "La classica pizza con prosciutto cotto",
                            Name = "Cotto",
                            Photo = "cotto.png",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "La classica pizza con la salsiccia",
                            Name = "Salsiccia",
                            Photo = "salsiccia.png",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "La classica pizza vegetariana",
                            Name = "Ortolana",
                            Photo = "ortolana.png",
                            Price = 6.50m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "La classica pizza bianca",
                            Name = "Marinara",
                            Photo = "marinara.png",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "La classica pizza di mare",
                            Name = "Salmone e Rucola",
                            Photo = "salmone_e_rucola.png",
                            Price = 8.00m
                        });
                });

            modelBuilder.Entity("la_mia_pizzeria_crud_mvc.Models.Pizza", b =>
                {
                    b.HasOne("la_mia_pizzeria_crud_mvc.Models.Category", "Category")
                        .WithMany("Pizzas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("la_mia_pizzeria_crud_mvc.Models.Category", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
